# Generated by Django 3.2.14 on 2022-07-18 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_anonpostview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
