# Generated by Django 3.2.14 on 2022-07-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_comment_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonPostView',
        ),
    ]
